### ISSUE TITLE
Can't generate a pdf

### ISSUE THREAD

**Issue by gumplei** [staempfli/magento2-module-pdf#1]
I am using Magento 2.1.3 and running in Ubuntu. 

The module can't generate the pdf after installation, I got the following error

```
 Failed without error message: /usr/bin/wkhtmltopdf.sh '/tmp/tmp_wkhtmlto_pdf_Mau6Ub.html' '/var/www/html/src/var/tmp/tmp_wkhtmlto_pdf_qezFwP.pdf'
#0 /var/www/html/src/vendor/staempfli/magento2-module-pdf/Model/View/PdfResult.php(109): Staempfli\Pdf\Adapter\WkPdfFile->toString()
#1 /var/www/html/src/vendor/staempfli/magento2-module-pdf/Model/View/PdfResult.php(74): Staempfli\Pdf\Model\View\PdfResult->renderPdf()
#2 /var/www/html/src/vendor/magento/framework/Controller/AbstractResult.php(124): Staempfli\Pdf\Model\View\PdfResult->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#3 /var/www/html/src/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\Controller\AbstractResult->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#4 /var/www/html/src/vendor/magento/framework/Interception/Chain/Chain.php(70): Staempfli\Pdf\Model\View\PdfResult\Interceptor->___callParent('renderResult', Array)
#5 /var/www/html/src/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Staempfli\\Pdf\\M...', 'renderResult', Object(Staempfli\Pdf\Model\View\PdfResult\Interceptor), Array, 'result-varnish-...')
#6 /var/www/html/src/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#7 /var/www/html/src/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Staempfli\Pdf\Model\View\PdfResult\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#8 /var/www/html/src/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Staempfli\\Pdf\\M...', 'renderResult', Object(Staempfli\Pdf\Model\View\PdfResult\Interceptor), Array, 'result-builtin-...')
#9 /var/www/html/src/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Staempfli\Pdf\Model\View\PdfResult\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#10 /var/www/html/src/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Staempfli\Pdf\Model\View\PdfResult\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#11 /var/www/html/src/var/generation/Staempfli/Pdf/Model/View/PdfResult/Interceptor.php(26): Staempfli\Pdf\Model\View\PdfResult\Interceptor->___callPlugins('renderResult', Array, Array)
#12 /var/www/html/src/vendor/magento/framework/App/Http.php(139): Staempfli\Pdf\Model\View\PdfResult\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#13 /var/www/html/src/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#14 /var/www/html/src/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#15 {main}
```

During the genreate process, the module didn't generate the /tmp/tmp_wkhtmlto_pdf_Mau6Ub.html for wkhtmltopdf to convert to pdf file.

**Comment by mhauri** [comment]
What's inside the wkhtmltopdf.sh?
The best would be to use the [binary](https://wkhtmltopdf.org/downloads.html) directly.

**Comment by mhauri** [comment]
Closed due to missing feedback. Please feel free to reopen if it's needed @gumplei .
